version: '2'
services:
  api:
    build:
      context: .
    ports:
      - "8001:8001"
    depends_on:
     - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: passity
      POSTGRES_DB: passity

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "8080:80"
    depends_on:
      - api
