name: passity
version: 0.0.1
description: A secure password keeper
author: Corentin Pillet <corentin@liner.io>
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  args: 0.12.2+6
  redstone:
    git: https://github.com/redstone-dart/redstone.git
  redstone_mapper:
     git: https://github.com/redstone-dart/redstone_mapper.git
  redstone_mapper_pg:
    path: dependencies/redstone_mapper_pg
  dart_jwt: "^0.4.5"
  yaml: "^2.1.8"
  cipher: any
  shelf_proxy: 0.1.0+2
  angular2: "^2.0.0-beta.8"
  browser: ^0.10.0
  less_dart: any
  dart_to_js_script_rewriter: ^0.1.0
transformers:
- angular2:
    platform_directives:
      - 'package:angular2/common.dart#CORE_DIRECTIVES'
      - 'package:angular2/common.dart#FORM_DIRECTIVES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
- less_dart
